[workspace]
members = [".", "analycore"]

[workspace.dependencies]
log = "0.4.22"

[package]
name = "elimclone"
version = "0.1.0"
edition = "2021"

[dependencies]
analycore.path = "./analycore"
log.workspace = true
simple_logger = "5.0.0"
